# coding=utf-8


def get_config(participant, session):
    return CONFIG[participant][session]


CONFIG = {
    'p10': {
        '0': 'none',
        '-1': 'text_short',
        '-2': 'image_short',

        '1': 'image_short',
        '2': 'text_short',
        '3': 'image_long',
        '4': 'text_long',
    },

    'p0': {
        '0': 'none',
        '-2': 'text_short',
        '-1': 'image_short',

        '1': 'image_short',
        '2': 'text_short',
        '3': 'image_long',
        '4': 'text_long',
    },

    'p1': {
        '0': 'none',
        '-2': 'text_short',
        '-1': 'image_short',

        '1': 'image_short',
        '2': 'text_short',
        '3': 'image_long',
        '4': 'text_long',
    },
    'p2': {
        '0': 'none',
        '-1': 'text_short',
        '-2': 'image_short',

        '2': 'image_short',
        '1': 'text_short',
        '4': 'image_long',
        '3': 'text_long',
    },

    'p3': {
        '0': 'none',
        '-2': 'text_short',
        '-1': 'image_short',

        '3': 'image_short',
        '4': 'text_short',
        '1': 'image_long',
        '2': 'text_long',
    },
    'p4': {
        '0': 'none',
        '-1': 'text_short',
        '-2': 'image_short',

        '4': 'image_short',
        '3': 'text_short',
        '2': 'image_long',
        '1': 'text_long',
    },

    'p5': {
        '0': 'none',
        '-2': 'text_short',
        '-1': 'image_short',

        '1': 'image_short',
        '2': 'text_short',
        '3': 'image_long',
        '4': 'text_long',
    },
    'p6': {
        '0': 'none',
        '-1': 'text_short',
        '-2': 'image_short',

        '4': 'image_short',
        '1': 'text_short',
        '2': 'image_long',
        '3': 'text_long',
    },
    'p7': {
        '0': 'none',
        '-2': 'text_short',
        '-1': 'image_short',

        '3': 'image_short',
        '4': 'text_short',
        '1': 'image_long',
        '2': 'text_long',
    },
    'p8': {
        '0': 'none',
        '-1': 'text_short',
        '-2': 'image_short',

        '2': 'image_short',
        '3': 'text_short',
        '4': 'image_long',
        '1': 'text_long',
    },
}


# return the <string> suffix
def get_icon_suffix(participant, icon_name):
    suffix = PARTICIPANT_ICON_SUFFIX[participant].get(icon_name)
    if suffix is None:
        print(f'Unsupported icon_name = [{icon_name}] for participant = [{participant}]')
        suffix = '4'

    return suffix


PARTICIPANT_ICON_SUFFIX = {
    'p10': {
        'img_message': '4',
        'img_birthday': '4',
        'img_alarm': '4',
        'img_meeting': '4',
        'img_meet': '4',
        'img_lunch': '4',
        'img_coffee': '4',
        'img_milk_eggs': '4',
        'img_credit_card': '4',
        'img_pin': '4',

        'img_leave': '4',
        'img_visitor': '4',
        'img_presentation': '4',
        'img_doctor': '4',
        'img_cleaning': '4',
        'img_delivery': '4',
        'img_email': '4',
        'img_send': '4',
        'img_reply': '4',
        'img_forward': '4',

        'img_buy': '4',
        'img_order_online': '4',
        'img_call': '4',
        'img_movie': '4',
        'img_ticket': '4',
        'img_battery_low': '4',
        'img_car': '4',
        'img_bus': '4',
        'img_flight': '4',
        'img_topup_cash': '4',

        'img_pay_rent': '4',
        'img_pay_cash': '4',
        'img_pay_mobile': '4',
        'img_id_card': '4',
        'img_licence': '4',
        'img_backup_computer': '4',
        'img_download': '4',
        'img_delete': '4',
        'img_valentine_day': '4',
        'img_mom_day': '4',

        'img_exercise': '4',
        'img_yoga': '4',
        'img_standup': '4',
        'img_cycling': '4',
        'img_swimming': '4',
        'img_take_photo': '4',
        'img_sync_photos': '4',
    },

    'p0': {
        'img_birthday': '4',
        'img_alarm': '1',
        'img_meeting': '2',
        'img_lunch': '3',
        'img_coffee': '3',
        'img_milk_eggs': '3',
        'img_credit_card': '5',
        'img_delivery': '4',
        'img_email': '1',
        'img_reply': '5',

        'img_leave': '1',
        'img_visitor': '2',
        'img_presentation': '2',
        'img_doctor': '2',
        'img_exercise': '1',
        'img_standup': '4',
        'img_swimming': '1',
        'img_take_photo': '5',
        'img_sync_photos': '2',
        'img_download': '1',

        'img_order_online': '1',
        'img_call': '1',
        'img_movie': '5',
        'img_valentine_day': '4',
        'img_mom_day': '4',
        'img_battery_low': '1',
        'img_car': '4',
        'img_bus': '1',
        'img_flight': '4',
        'img_topup_cash': '2',

        'img_pay_rent': '1',
        'img_pay_cash': '4',
        'img_licence': '1',
        'img_backup_computer': '4',
    },

    'p1': {
        'img_message': '2',
        'img_birthday': '2',
        'img_alarm': '1',
        'img_meeting': '2',
        'img_meet': '4',
        'img_lunch': '3',
        'img_coffee': '2',
        'img_milk_eggs': '2',
        'img_credit_card': '2',
        'img_pin': '4',

        'img_leave': '2',
        'img_visitor': '2',
        'img_presentation': '2',
        'img_doctor': '2',
        'img_cleaning': '1',
        'img_delivery': '2',
        'img_email': '4',
        'img_send': '4',
        'img_reply': '4',
        'img_forward': '4',

        'img_buy': '3',
        'img_order_online': '3',
        'img_call': '1',
        'img_movie': '2',
        'img_ticket': '1',
        'img_battery_low': '1',
        'img_car': '2',
        'img_bus': '3',
        'img_flight': '4',
        'img_topup_cash': '4',

        'img_pay_rent': '3',
        'img_pay_cash': '1',
        'img_pay_mobile': '2',
        'img_id_card': '1',
        'img_licence': '3',
        'img_backup_computer': '3',
        'img_download': '2',
        'img_delete': '1',
        'img_valentine_day': '1',
        'img_mom_day': '1',

        'img_exercise': '1',
        'img_yoga': '2',
        'img_standup': '1',
        'img_cycling': '1',
        'img_swimming': '1',
        'img_take_photo': '2',
        'img_sync_photos': '3',
    },
    'p2': {
        'img_message': '4',
        'img_birthday': '1',
        'img_alarm': '1',
        'img_meeting': '2',
        'img_meet': '1',
        'img_lunch': '3',
        'img_coffee': '3',
        'img_milk_eggs': '2',
        'img_credit_card': '3',
        'img_pin': '4',

        'img_leave': '3',
        'img_visitor': '4',
        'img_presentation': '2',
        'img_doctor': '2',
        'img_cleaning': '4',
        'img_delivery': '1',
        'img_email': '4',
        'img_send': '4',
        'img_reply': '2',
        'img_forward': '2',

        'img_buy': '1',
        'img_order_online': '1',
        'img_call': '3',
        'img_movie': '3',
        'img_ticket': '3',
        'img_battery_low': '4',
        'img_car': '4',
        'img_bus': '1',
        'img_flight': '4',
        'img_topup_cash': '3',

        'img_pay_rent': '2',
        'img_pay_cash': '3',
        'img_pay_mobile': '4',
        'img_id_card': '1',
        'img_licence': '1',
        'img_backup_computer': '4',
        'img_download': '4',
        'img_delete': '1',
        'img_valentine_day': '4',
        'img_mom_day': '1',

        'img_exercise': '1',
        'img_yoga': '1',
        'img_standup': '4',
        'img_cycling': '2',
        'img_swimming': '3',
        'img_take_photo': '1',
        'img_sync_photos': '4',
    },

    'p3': {
        'img_birthday': '3',
        'img_alarm': '1',
        'img_meeting': '2',
        'img_lunch': '3',
        'img_coffee': '2',
        'img_milk_eggs': '3',
        'img_credit_card': '1',
        'img_delivery': '4',
        'img_email': '4',
        'img_reply': '2',

        'img_leave': '1',
        'img_visitor': '2',
        'img_presentation': '4',
        'img_doctor': '4',
        'img_exercise': '1',
        'img_standup': '4',
        'img_swimming': '1',
        'img_take_photo': '2',
        'img_sync_photos': '2',
        'img_download': '4',

        'img_order_online': '2',
        'img_call': '1',
        'img_movie': '3',
        'img_valentine_day': '1',
        'img_mom_day': '4',
        'img_battery_low': '1',
        'img_car': '1',
        'img_bus': '1',
        'img_flight': '1',
        'img_topup_cash': '2',

        'img_pay_rent': '1',
        'img_pay_cash': '4',
        'img_licence': '1',
        'img_backup_computer': '3',
    },

    'p4': {
        'img_birthday': '2',
        'img_alarm': '4',
        'img_meeting': '2',
        'img_lunch': '4',
        'img_coffee': '3',
        'img_milk_eggs': '1',
        'img_credit_card': '4',
        'img_delivery': '1',
        'img_email': '3',
        'img_reply': '2',

        'img_leave': '3',
        'img_visitor': '2',
        'img_presentation': '3',
        'img_doctor': '4',
        'img_exercise': '1',
        'img_standup': '3',
        'img_swimming': '4',
        'img_take_photo': '1',
        'img_sync_photos': '2',
        'img_download': '1',

        'img_order_online': '4',
        'img_call': '1',
        'img_movie': '4',
        'img_valentine_day': '4',
        'img_mom_day': '4',
        'img_battery_low': '2',
        'img_car': '3',
        'img_bus': '4',
        'img_flight': '4',
        'img_topup_cash': '2',

        'img_pay_rent': '1',
        'img_pay_cash': '1',
        'img_licence': '3',
        'img_backup_computer': '3',
    },

    'p5': {
        'img_birthday': '1',
        'img_alarm': '1',
        'img_meeting': '4',
        'img_lunch': '3',
        'img_coffee': '2',
        'img_milk_eggs': '4',
        'img_credit_card': '3',
        'img_delivery': '4',
        'img_email': '4',
        'img_reply': '2',

        'img_leave': '3',
        'img_visitor': '2',
        'img_presentation': '4',
        'img_doctor': '3',
        'img_exercise': '1',
        'img_standup': '4',
        'img_swimming': '1',
        'img_take_photo': '1',
        'img_sync_photos': '2',
        'img_download': '1',

        'img_order_online': '4',
        'img_call': '1',
        'img_movie': '3',
        'img_valentine_day': '3',
        'img_mom_day': '4',
        'img_battery_low': '1',
        'img_car': '1',
        'img_bus': '4',
        'img_flight': '4',
        'img_topup_cash': '1',

        'img_pay_rent': '4',
        'img_pay_cash': '2',
        'img_licence': '1',
        'img_backup_computer': '1',
    },

    'p6': {
        'img_birthday': '2',
        'img_alarm': '1',
        'img_meeting': '4',
        'img_lunch': '4',
        'img_coffee': '3',
        'img_milk_eggs': '2',
        'img_credit_card': '4',
        'img_delivery': '4',
        'img_email': '4',
        'img_reply': '1',

        'img_leave': '1',
        'img_visitor': '2',
        'img_presentation': '3',
        'img_doctor': '1',
        'img_exercise': '3',
        'img_standup': '1',
        'img_swimming': '1',
        'img_take_photo': '1',
        'img_sync_photos': '2',
        'img_download': '1',

        'img_order_online': '4',
        'img_call': '1',
        'img_movie': '3',
        'img_valentine_day': '4',
        'img_mom_day': '1',
        'img_battery_low': '2',
        'img_car': '2',
        'img_bus': '4',
        'img_flight': '4',
        'img_topup_cash': '4',

        'img_pay_rent': '1',
        'img_pay_cash': '4',
        'img_licence': '3',
        'img_backup_computer': '3',
    },

    'p7': {
        'img_birthday': '4',
        'img_alarm': '1',
        'img_meeting': '2',
        'img_lunch': '2',
        'img_coffee': '3',
        'img_milk_eggs': '1',
        'img_credit_card': '3',
        'img_delivery': '4',
        'img_email': '1',
        'img_reply': '1',

        'img_leave': '1',
        'img_visitor': '1',
        'img_presentation': '3',
        'img_doctor': '2',
        'img_exercise': '1',
        'img_standup': '3',
        'img_swimming': '4',
        'img_take_photo': '2',
        'img_sync_photos': '1',
        'img_download': '4',

        'img_order_online': '1',
        'img_call': '1',
        'img_movie': '3',
        'img_valentine_day': '1',
        'img_mom_day': '4',
        'img_battery_low': '1',
        'img_car': '1',
        'img_bus': '1',
        'img_flight': '4',
        'img_topup_cash': '4',

        'img_pay_rent': '2',
        'img_pay_cash': '1',
        'img_licence': '1',
        'img_backup_computer': '4',
    },

    'p8': {
        'img_birthday': '3',
        'img_alarm': '1',
        'img_meeting': '1',
        'img_lunch': '4',
        'img_coffee': '1',
        'img_milk_eggs': '1',
        'img_credit_card': '4',
        'img_delivery': '4',
        'img_email': '1',
        'img_reply': '2',

        'img_leave': '2',
        'img_visitor': '2',
        'img_presentation': '4',
        'img_doctor': '4',
        'img_exercise': '1',
        'img_standup': '4',
        'img_swimming': '4',
        'img_take_photo': '4',
        'img_sync_photos': '2',
        'img_download': '1',

        'img_order_online': '4',
        'img_call': '1',
        'img_movie': '4',
        'img_valentine_day': '3',
        'img_mom_day': '2',
        'img_battery_low': '1',
        'img_car': '4',
        'img_bus': '4',
        'img_flight': '4',
        'img_topup_cash': '2',

        'img_pay_rent': '4',
        'img_pay_cash': '4',
        'img_licence': '1',
        'img_backup_computer': '1',
    },



}
